PrivateKey: APrivateKey1zkpFEdxSDijsKrhAXM8BFdMSPcnrq9ZACF7mXhxGVKyxyZN
ViewKey: AViewKey1rBv4ZQKH8YC85bErGXuojKD5tww3SJRk2GZGX9bwsY1v
Address: aleo1z6ee6qt5pfjt8ru7jtumsu6qv2vxgr8pw6t7uuv2nzsy40lgtqpqfdhwa8
ApiUrl: https://vm.aleo.org/api/testnet3/transaction/
RedisServer: 172.18.10.46:6379
Contract: health.aleo